apiVersion: v1
kind: Pod
metadata:
  name: oom-demo-fixed
  namespace: sre-lab
spec:
  restartPolicy: Always
  containers:
    - name: app
      image: python:3.12-alpine
      command: ["python", "-c", "import time; data=bytearray(64*1024*1024); time.sleep(3600)"]
      resources:
        requests:
          memory: 96Mi
        limits:
          memory: 160Mi
