apiVersion: v1
kind: Pod
metadata:
  name: crashloop-demo-fixed
  namespace: sre-lab
spec:
  containers:
    - name: app
      image: busybox:1.36
      command: ["sh", "-c", "echo ready; sleep 3600"]
